var mongoose = require("mongoose"),
    Campground =require("./models/campground"),
    Comment=require("./models/comments")

 var Data=[{name:"Madurai",image:"https://www.tamilnadutourism.com/blog/wp-content/uploads/2019/10/madurai-768x395.jpg",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id metus id nunc tempus tristique. Morbi risus risus, iaculis eu efficitur non, gravida non risus. Integer placerat tellus id ipsum dictum rutrum. Nunc sit amet quam posuere, tempor tellus aliquam, hendrerit justo. Cras accumsan ligula lorem, a lacinia ante sagittis eget. Etiam tempus in nulla vitae vehicula. In ornare arcu neque, nec congue nisl feugiat facilisis. Morbi enim dui, molestie non arcu nec, semper rhoncus ipsum. Duis ex nunc, rutrum id sollicitudin eget, rhoncus accumsan elit. Ut a risus metus. Maecenas ac accumsan leo, nec ultricies risus. Nulla eu enim vitae diam lacinia vulputate. Curabitur eget leo justo. Cras bibendum auctor est, et dictum magna volutpat a. Cras lacinia placerat condimentum. Maecenas sit amet venenatis leo. Etiam sit amet dignissim urna. Pellentesque placerat lectus accumsan mauris blandit, nec hendrerit lacus tincidunt. Quisque dignissim tellus leo, at cursus risus imperdiet at. Morbi tempus sed tellus at vulputate. In ac efficitur mauris. Sed at nisi vel erat commodo efficitur in eu quam."},
    {name:"Hyderabad",image:"https://static.toiimg.com/photo/62379342/.jpg",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id metus id nunc tempus tristique. Morbi risus risus, iaculis eu efficitur non, gravida non risus. Integer placerat tellus id ipsum dictum rutrum. Nunc sit amet quam posuere, tempor tellus aliquam, hendrerit justo. Cras accumsan ligula lorem, a lacinia ante sagittis eget. Etiam tempus in nulla vitae vehicula. In ornare arcu neque, nec congue nisl feugiat facilisis. Morbi enim dui, molestie non arcu nec, semper rhoncus ipsum. Duis ex nunc, rutrum id sollicitudin eget, rhoncus accumsan elit. Ut a risus metus. Maecenas ac accumsan leo, nec ultricies risus. Nulla eu enim vitae diam lacinia vulputate. Curabitur eget leo justo. Cras bibendum auctor est, et dictum magna volutpat a. Cras lacinia placerat condimentum. Maecenas sit amet venenatis leo. Etiam sit amet dignissim urna. Pellentesque placerat lectus accumsan mauris blandit, nec hendrerit lacus tincidunt. Quisque dignissim tellus leo, at cursus risus imperdiet at. Morbi tempus sed tellus at vulputate. In ac efficitur mauris. Sed at nisi vel erat commodo efficitur in eu quam."},
    {name:"Switzerland",image:"https://i.ytimg.com/vi/oZRBUBbfIJ8/maxresdefault.jpg",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id metus id nunc tempus tristique. Morbi risus risus, iaculis eu efficitur non, gravida non risus. Integer placerat tellus id ipsum dictum rutrum. Nunc sit amet quam posuere, tempor tellus aliquam, hendrerit justo. Cras accumsan ligula lorem, a lacinia ante sagittis eget. Etiam tempus in nulla vitae vehicula. In ornare arcu neque, nec congue nisl feugiat facilisis. Morbi enim dui, molestie non arcu nec, semper rhoncus ipsum. Duis ex nunc, rutrum id sollicitudin eget, rhoncus accumsan elit. Ut a risus metus. Maecenas ac accumsan leo, nec ultricies risus. Nulla eu enim vitae diam lacinia vulputate. Curabitur eget leo justo. Cras bibendum auctor est, et dictum magna volutpat a. Cras lacinia placerat condimentum. Maecenas sit amet venenatis leo. Etiam sit amet dignissim urna. Pellentesque placerat lectus accumsan mauris blandit, nec hendrerit lacus tincidunt. Quisque dignissim tellus leo, at cursus risus imperdiet at. Morbi tempus sed tellus at vulputate. In ac efficitur mauris. Sed at nisi vel erat commodo efficitur in eu quam."}]

function seedDB(){
    Campground.deleteMany({},function(err){
        
    })

   
     
}

module.exports=seedDB;
